# Generated by Django 2.2 on 2021-04-10 23:55

from django.db import migrations, models
import django.db.models.deletion
import lawyer_services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Firm')),
                ('email', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('has_gst_number', models.BooleanField(default=False)),
                ('tncs_file', models.FileField(null=True, upload_to=lawyer_services.models.get_pdf_invoice_upload_path)),
                ('contact_number', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WitnessService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, default='WITNESS', max_length=100)),
                ('review_type', models.CharField(choices=[('EN', 'English Review'), ('CN', 'Chinese Review')], default='EN', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_services.Firm')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_services_witnessservice', to='core.WillOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, default='WITNESS', max_length=100)),
                ('review_type', models.CharField(choices=[('EN', 'English Review'), ('CN', 'Chinese Review')], default='EN', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_services.Firm')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_services_reviewservice', to='core.WillOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LPACertificateService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, default='WITNESS', max_length=100)),
                ('review_type', models.CharField(choices=[('EN', 'English Review'), ('CN', 'Chinese Review')], default='EN', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer_services.Firm')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_services_lpacertificateservice', to='core.WillOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
