# Generated by Django 2.2 on 2021-04-10 23:55

import billing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_category', models.CharField(choices=[('PARTNER_DISCOUNT', 'Partner Discount'), ('REFERRAL_DISCOUNT', 'Referral Discount'), ('GENERAL_DISCOUNT', 'General Discount'), ('ABANDONED_CART_DISCOUNT', 'Abandoned Cart Discount')], default='REFERRAL_DISCOUNT', max_length=25)),
                ('discount_type', models.CharField(choices=[('NO_DISCOUNT', 'No Discount'), ('PERCENTAGE', 'Percent Discount'), ('FIXED_PRICE', 'Fixed Price Discount')], default='FIXED_PRICE', max_length=25)),
                ('discount_target', models.CharField(choices=[('WILL_PRICE', 'Will Price Discount'), ('SERVICES_PRICE', 'Service Price Discount'), ('FULL_PRICE', 'Full Discount')], default='WILL_PRICE', max_length=25)),
                ('discount_amount', models.DecimalField(decimal_places=2, default='9.90', max_digits=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_category', models.CharField(choices=[('PARTNER_DISCOUNT', 'Partner Discount'), ('REFERRAL_DISCOUNT', 'Referral Discount'), ('GENERAL_DISCOUNT', 'General Discount'), ('ABANDONED_CART_DISCOUNT', 'Abandoned Cart Discount')], default='REFERRAL_DISCOUNT', max_length=25)),
                ('discount_type', models.CharField(choices=[('NO_DISCOUNT', 'No Discount'), ('PERCENTAGE', 'Percent Discount'), ('FIXED_PRICE', 'Fixed Price Discount')], default='FIXED_PRICE', max_length=25)),
                ('discount_target', models.CharField(choices=[('WILL_PRICE', 'Will Price Discount'), ('SERVICES_PRICE', 'Service Price Discount'), ('FULL_PRICE', 'Full Discount')], default='WILL_PRICE', max_length=25)),
                ('discount_amount', models.DecimalField(decimal_places=2, default='9.90', max_digits=100)),
                ('discount_code', models.CharField(max_length=526, unique=True)),
                ('redeemed', models.IntegerField(blank=True, default=0, null=True)),
                ('max_redeemed', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('gross_price', models.DecimalField(decimal_places=2, default=49.9, max_digits=100)),
                ('net_price', models.DecimalField(decimal_places=2, default=49.9, max_digits=100)),
                ('net_price_after_card_fees', models.DecimalField(decimal_places=2, default=49.9, max_digits=100)),
                ('card_fees', models.DecimalField(decimal_places=2, default=49.9, max_digits=100)),
                ('been_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.IntegerField(blank=True, default=7)),
                ('expiry_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('discounts', models.ManyToManyField(blank=True, to='billing.Discount')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.CharField(blank=True, max_length=256)),
                ('limit', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_limit', to='billing.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_pdf', models.FileField(null=True, upload_to=billing.models.get_pdf_invoice_upload_path)),
                ('version', models.IntegerField(default=1)),
                ('downloaded', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_repo', to='billing.Invoice')),
            ],
        ),
    ]
