# Generated by Django 2.2 on 2021-04-10 23:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WillOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=120, unique=True)),
                ('order_type', models.CharField(choices=[('WILL', 'Will'), ('LPA', 'LPA'), ('SCHEDULE_OF_ASSETS', 'Schedule of Assets'), ('CUSTODY', 'CUSTODY')], max_length=120)),
                ('tncs', models.BooleanField(default=False)),
                ('disclaimer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WillRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GENERATED', 'Generated Will'), ('USER_UPLOADED', 'Uploaded Will'), ('LAWYER_AMENDED', 'Lawyer Amended')], default='GENERATED', max_length=120)),
                ('will', models.FileField(null=True, upload_to=core.models.get_pdf_will_upload_path)),
                ('content', models.TextField(null=True)),
                ('version', models.IntegerField(default=1)),
                ('downloaded', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='will_repo', to='core.WillOrder')),
            ],
        ),
    ]
