# Generated by Django 2.2 on 2021-04-10 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partners',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstore',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_store', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstore',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_stores', to='partners.Partners'),
        ),
        migrations.AddField(
            model_name='applicationstore',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
