# Generated by Django 2.2 on 2021-04-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WillLastRites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('funeral_religion', models.CharField(blank=True, choices=[('NON_RELIGIOUS', 'Non-religious'), ('CHRISTIAN', 'Christian'), ('HINDU', 'Hindu'), ('BUDDHIST', 'Buddhist'), ('TAOIST', 'Taoist'), ('CATHOLIC', 'Catholic'), ('SIKH', 'Sikh')], max_length=256, verbose_name='Religion for Funeral Rites')),
                ('funeral_location', models.CharField(blank=True, max_length=256, verbose_name='Location of Funeral')),
                ('funeral_duration', models.IntegerField(blank=True, null=True, verbose_name='Duration of Funeral (Days)')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_rites', to='core.WillOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WillInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.CharField(blank=True, choices=[('CREMATED', 'Held at a crematorium'), ('BURIED', 'Buried in Singapore'), ('SCATTERED', 'Scattered in the Sea')], max_length=256, verbose_name='Instructions')),
                ('crematorium_location', models.CharField(blank=True, choices=[('MANDAI_CREMATORIUM_AND_COLUMBARIUM_COMPLEX', 'Mandai Crematorium and Columbarium Complex'), ('CHOA_CHU_KANG_COLUMBARIUM', 'Choa Chu Kang Columbarium'), ('TSE_TOH_AUM_TEMPLE', 'Tse Toh Aum Temple'), ('KONG_MENG_SAN_PHOR_KARK_SEE_MONASTERY', 'Kong Meng San Phor Kark See Monastery')], max_length=256, null=True, verbose_name='Crematorium Location')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.WillOrder')),
            ],
        ),
    ]
