WILL_ORDER = 'WILL'
LPA_ORDER = 'LPA'
SCHEDULE_OF_ASSETS_ORDER = 'SCHEDULE_OF_ASSETS'
CUSTODY_ORDER = 'CUSTODY'
ORDER_TYPES = (
    (WILL_ORDER, "Will"),
    (LPA_ORDER, "LPA"),
    (SCHEDULE_OF_ASSETS_ORDER, "Schedule of Assets"),
    (CUSTODY_ORDER, "CUSTODY"),
)
