# Generated by Django 2.2 on 2021-04-10 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doneepowers',
            name='donee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donee_powers', related_query_name='donee', to='persons.EntityStore', verbose_name='Donee'),
        ),
        migrations.AddField(
            model_name='doneepowers',
            name='named_main_donee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='named_replacement_donee', to='persons.EntityStore', verbose_name='Named Replacement'),
        ),
    ]
