# Generated by Django 2.2 on 2021-04-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAndAffairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jointly_severally', models.CharField(blank=True, choices=[('JOINTLY', 'Jointly'), ('JOINTLY_AND_SEVERALLY', 'Jointly and Severally')], help_text='Joint And Severally: Any one of your donees can make decisions for you. <br/> Jointly: All decisions must be agreed by both donees. If they are unable to agree on a particular issue, then both donees cannot act on your behalf for that issue.', max_length=30, null=True, verbose_name='Mode of Acting')),
                ('power_to_give_cash', models.CharField(choices=[('Unrestricted', 'Unrestricted'), ('Restricted', 'Restricted'), ('Not_Allowed', 'Not Allowed')], default='NO', help_text='If you select Unrestricted, your donee may sell your non-residential property and make gifts on your behalf, but the remaining cash <u>must be sufficient for your financial support</u>.', max_length=30, verbose_name='Power to Sell Non-residential Property and Give Cash Gifts')),
                ('cash_restriction', models.DecimalField(blank=True, decimal_places=2, help_text='The total value of the gifts that your donee may make on your behalf in one calendar year is limited to this amount.', max_digits=10, null=True, verbose_name='Restriction on Cash Gifts (Max Amount)')),
                ('power_to_sell_property', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='NO', help_text='If you select No, your donee would have to seek the court’s approval to sell, transfer, mortgage, or otherwise deal with and affect your interest in your residential property.', max_length=30, verbose_name='Power to Sell/Rent/Mortgage Residential Property')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_and_affairs_restrictions', to='core.WillOrder')),
                ('restricted_asset', models.ForeignKey(blank=True, help_text='This property may not be sold, transfered, mortgaged, or otherwise dealt with without court approval.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricted_asset', to='assets.AssetStore', verbose_name='Restricted Property')),
                ('restricted_property', models.ForeignKey(blank=True, help_text='This property may not be sold, transfered, mortgaged, or otherwise dealt with without court approval.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricted_property', to='assets.RealEstate', verbose_name='Restricted Property')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWelfare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_to_refuse', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], help_text='This includes power to give or refuse consent to start or continue your treatments, including clinical trials (which involve the testing of new health substances such as medication or medical devices).', max_length=30, verbose_name='Power to Refuse or Accept Medical Treatment')),
                ('jointly_severally', models.CharField(blank=True, choices=[('JOINTLY', 'Jointly'), ('JOINTLY_AND_SEVERALLY', 'Jointly and Severally')], help_text='Joint And Severally: Any one of your donees can make decisions for you. <br/> Jointly: All decisions must be agreed by both donees. If they are unable to agree on a particular issue, then both donees cannot act on your behalf for that issue.', max_length=30, null=True, verbose_name='Mode of Acting')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_welfare_restrictions', to='core.WillOrder')),
            ],
        ),
    ]
