# Generated by Django 2.2 on 2021-04-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipsKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('step', models.CharField(choices=[('YOUR_DETAILS', 'Your Details'), ('SPECIFIC_ASSETS', 'Specific Assets'), ('RESIDUAL_ASSETS', 'Residual Assets'), ('APPOINTMENTS', 'Appointments'), ('ARRANGEMENTS', 'Arrangements'), ('SUMMARY', 'Summary'), ('CHECKOUT', 'Checkout')], max_length=20)),
                ('order_type', models.CharField(choices=[('ALL', 'All'), ('WILL', 'WILL')], max_length=20)),
                ('tip_type', models.CharField(choices=[('KEY_WORDS', 'Key Words'), ('DID_YOU_KNOW', 'Did You Know')], max_length=20)),
            ],
        ),
    ]
